print("Jesus Christ Our Lord And Savior")
print("hello world")
print("my name is Tsotne")
print(" I'm 17 years old")
print("my goal")
print("is to")
print("be a")
print("succesful man")
print("I want")
print("to be")
print("Like Chad")
print("my first")
print("goal is")
print("to get")
print("into tavisufali")
print("university")
print("math and computer science")
print("MAQS program")
print("my favorite")
print("subject is")
print("mathematics ")
print("I'm working")
print("hard to get")
print("maximum point")
print("in mathematics exam")
print("I hate Satan")
print("if i work hard")
print("enough it will happen")
print("my goal is to become Game developer")
print("I want to help")
print("My family with my future great job")
print("I also want to build my own christian church")
print("I Love jesus and want to introduce to anyone")
print("I love Holy Spirit")
print("I love god the father")
print("I also want to help many people who need my help")
print("If i ever will be succesful enough")
print("I will do good things")
print("I love my family <3 ")
print("I love everyone <3")
print("My favourite Bible verses are")
print("phillipians4:13")
print("May God bless and Protect us all and forgive us sinners <3 ")